### ISSUE TITLE
Not Able To Find Metadata for Doom iwad (or anything else)

### ISSUE THREAD

**Issue by TheDiggleGod** [nstlaurent/DoomLauncher#194]
When I "Update Metadata" for my Doom iwad, it just shows a bunch of random community wads:

![image](https://user-images.githubusercontent.com/60529987/93834337-860c8100-fc49-11ea-8c81-a06ad3644a42.png)

Searching for metadata on nearly every other file I have returns this error:

![image](https://user-images.githubusercontent.com/60529987/93834342-8c026200-fc49-11ea-896d-b2e62c842519.png)

I then checked every mirror in the settings, but none of them worked. Here's a pic of my settings incase something's weird:

![image](https://user-images.githubusercontent.com/60529987/93834331-80af3680-fc49-11ea-8e3a-1fc0ed109d50.png)

I don't know a lot about what's helpful to include on bug reports like this, so let me know if there's something stupid I did wrong or didn't include. Thanks : )

**Comment by nstlaurent** [comment]
Hi,

This is because the IWADs are not on the idgames mirror, otherwise it would be illegal. It took me a few minutes to realize what is going on. For whatever reason when you search 'doom' the idgames API just returns any file containing the word 'doom' instead of saying not found.

I can add a warning saying you are searching for an IWAD in the next release. Thanks for the report!

**Comment by TheDiggleGod** [comment]
Thanks. I think I was also misunderstood about what the idgames archive was. I thought it was like a tvDB or something, where it has info on every Doom wad that people care to submit info for, so that's probably a bit on me.

**Comment by nstlaurent** [comment]
Completed on development.
