### ISSUE TITLE
.rar archive support

### ISSUE THREAD

**Issue by EduardDiego** [nstlaurent/DoomLauncher#217]
I think this is due to rar being a proprietary file format, but is there a chance for rar support in the future? Seems like many wad files was archived as rar's, so you need to spend time to mess around with file formats.

**Comment by CortexReaver** [comment]
and 7zip as well

**Comment by nstlaurent** [comment]
I'm working on this now and it will be available in the next release. They will be automatically transformed to zip files when importing a rar or 7z.

**Comment by CortexReaver** [comment]
So will it duplicate files? Why not just use 7zip and rar as it using zip?

**Comment by CortexReaver** [comment]
Also all this archiving\unzipping gets more complicated every time... Maybe just remove all archive support and instead just use subfolders? Wad's and pk's are already an archives itself.

**Comment by nstlaurent** [comment]
These formats are incredibly clumsy to deal with. Doom Launcher was built around using zip archives specifically. The archive support is never going to be removed. It's the core functionality and would break most of the user base since this application has existed this way since 2014. The unmanaged stuff is relatively new and was never really intended to manage your entire library. I understand you can do that, but there is practically no purpose in doing it this way.

I'm also not sure what you mean by throwing into a folder and synchronizing. If you are talking about the 'Sync Status' option that's not what it was intended for. That is a feature for dealing with files that are missing because the user deleted them or copied it somewhere without all the game files.

Both wads and pks are already 'archives' but wads are not compressed wasting space. Doom Launcher uses the zip archive to both compress all the contents and keep everything together. There are a lot of files on idgames that come packaged with deh files and other wads that are packaged inside of a zip. Downloading a file like this from idgames means a something packaged with a main .wad file a .wad texture file and a .deh file are automatically handled in one package.

If you do not want to use the managed setting, that is OK but there are going to be limitations. I don't entirely understand why you are worried about duplication. It would only be duplicated if you kept the downloaded file after adding it to Doom Launcher. Either download it from idgames, or drag and drop the file to Doom Launcher. Once it's added to Doom Launcher in managed mode you can delete the original.

**Comment by CortexReaver** [comment]
Well, there are some nuances that need to be pointed out.
 First, import and then deletion. Unless it is some jerk with OCD like me, not everyone will remember to clean original files. So yes, it is doubling the size.
 Next, DoomLauncher need to unpack those zips to be able to launch them. So it's tripling the size. And this is why I see no point in archiving stuff, because all this gets bloated soon. At least write a disclaimer, and a warning to not put GameFiles folder on an SSD that is going to wear three times faster.
 I am not trying to convince you for redoing all the hard work from scratch, or changing its "core principle". Just shedding light on how things are, despite the creator's intention.

**Comment by CortexReaver** [comment]
Oh, by the way. You can add option "delete original after import" for better automation... if possible. It'll smooth the experience a little.
