### ISSUE TITLE
Add source port statdump support for From Doom With Love

### ISSUE THREAD

**Issue by AbrahamGoldberg** [nstlaurent/DoomLauncher#244]
Hello, this is just like request #223 ( https://github.com/nstlaurent/DoomLauncher/issues/223 ) except for the source port From Doom With Love.

**Comment by nstlaurent** [comment]
Sure. I'm probably going to work on an update so these will be easier to add, since these forks have been happening a lot lately. In the meantime, you can work around this by renaming the executable to any of the base ports (prboom.exe, or dsda-doom.exe) Doom Launcher just determines it by the exe name so the statistics feature will become available. You can still leave the display in Doom Launcher fdwl or whatever you like.
