### ISSUE TITLE
perhaps a false positive...

### ISSUE THREAD

**Issue by eskoONE** [nstlaurent/DoomLauncher#247]
..., but id like an explanation as to why this might be happening please.

https://www.hybrid-analysis.com/sample/387cbe1b5d5ccae8f58e78b28e792a2c9c8455840d749db39c5ec5683cb9cd70

**Comment by nstlaurent** [comment]
It's a false positive. It's flagging System.Data.SQLite.dll which is the library used to read the sqlite database. I've tested Doom Launcher on another website previously (I can't remember which one) and everything came back clean. I've been working on upgrading some of the libraries since they are out of date, including the sqlite library that was flagged. The new version is not flagged by that site:

https://www.hybrid-analysis.com/sample/31385eeba4bba32ffdae64f88376f8dc4b627e1b8b099bdae4d646a40f770713

**Comment by eskoONE** [comment]
great, thanks for the update.

**Comment by nstlaurent** [comment]
I have been able to get the package building for the updated release:
https://ci.appveyor.com/project/hobomaster22/doomlauncher/builds/41784212/artifacts

This includes a lot of upgrades to references Doom Launcher uses including the .NET Framework. I do not expect any issues, but they can always occur in these type of updates. If you run this it should pass the check. If you run this release and have any issues please let me know.

**Comment by eskoONE** [comment]
i dont know whats happening but its still getting flagged. https://www.hybrid-analysis.com/sample/194e357b67f8f04cd30b723abf248467cde5690d8f0e268b25fd0886a8577202

i hope you can sort it out, but until then i wont be using it. sry for the inconvenience.

**Comment by nstlaurent** [comment]
Well, it's wrong. There is nothing malicious in the package and I'm not going to change it based on some random website incorrectly flagging it.
